apiVersion: apps/v1
kind: Deployment
metadata:
  name: giordano-tarefa3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: giordano-tarefa3
  template:
    metadata:
      labels:
        app: giordano-tarefa3
    spec:
      containers:
      - name: giordano-tarefa3
        image: alpine:latest
        command: ["sleep", "3600"]
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"
